### ISSUE TITLE
About BVH

### ISSUE THREAD

**Issue by miooooooooooo** [seanschneeweiss/RoSeMotion#5]
Can you share the code about converting 3D coordinate of hand to .bvh file.

**Comment by seanschneeweiss** [comment]
All files can be viewed within GitHub, its Open Source.
Take a look at 
https://github.com/seanschneeweiss/RoSeMotion/blob/9743e4060387589d2bcfa6a3a86cea8795d41f3e/app/LeapData.py#L172-L205
Especially the case where we use the basis from the first frame for all ongoing angle calculations 
https://github.com/seanschneeweiss/RoSeMotion/blob/9743e4060387589d2bcfa6a3a86cea8795d41f3e/app/LeapData.py#L184-L186

We calculate the rotation matrices between a selected bone and its parent bone. The skeleton is defined here:
https://github.com/seanschneeweiss/RoSeMotion/blob/9743e4060387589d2bcfa6a3a86cea8795d41f3e/app/config/Skeleton.py#L11-L38

To give an example: The root's basis is the identity matrix. The difference between the identity matrix and the forearm basis is the forearm basis itself.
If you look at the code, we have `basis` and `parent_basis`. `basis` is defined by the forearm basis, `parent_basis` is defined by root (identity). The difference is calculated by matrix multiplication: basis * parent_basis'
The `'` stands for transposing the matrices.

In case of the hand palm, the `parent_basis` is the one from the forearm and the `basis` is defined by the palm's basis. And so on.

We calculate the rotation matrices dependent from the first recorded basis (extracted from the first recorded frame). That is why the calculation looks as follows:
rotation = (initial_basis * basis') * (parent_initial_basis, parent_basis')'

The angles required for the BVH file are calculated from the rotation matrices (euler angles).

Let me know if this helps you and what requires more explanation. I would kindly inform you that this is part of a hopefully soon to be published publication (Open Access), although we just started the peer review (so no guarantee).
