### ISSUE TITLE
are you planning on  GEMINI wrapper for leap motion?

### ISSUE THREAD

**Issue by AdoHaha** [seanschneeweiss/RoSeMotion#9]
At least from release info, it is a large improvement.

**Comment by seanschneeweiss** [comment]
This mainly depends on the required effort to create the Python wrapper with SWIG. But we might give it a try - I agree, that Gemini sounds very promising.

**Comment by AdoHaha** [comment]
From what I understand, there were no changes in C API. One of my team members tried to compile it herself, but unfortunately to no effort -- we would love to be able to use the Python version. We will soon share the Python (windows) to (Linux) ROS bridge for passing the hand skeleton data to Robot Operating System, based on your wrapper. It would be cool to be able to use it with Gemini

**Comment by AdoHaha** [comment]
wow, thanks, we will try it soon

**Comment by AdoHaha** [comment]
Sorry for the long reply. The Gemini wrapper works well. One again, thank you

**Comment by seanschneeweiss** [comment]
Appreciate the feedback, thank you.
